from typing import Dict

REGION_NAMES: Dict[str, str] = {
    "fh_r1": "Farmlands",
    "fh_r1a": "Farmlands",
    "bc_r1": "Bear Cave",
    "hc_r1": "Farmer Basement",
    "cr_r1": "Crypt",
    "path2crypts": "Path to Crypts",
    "gd_b": "Crypt Entrance Dungeon",
    "fh_r3": "Path to Stonebridge",
    "bt_r1": "Stonebridge",
    "path2sd": "Path to Wesrin Cross",
    "path2sd_a": "Path to Wesrin Cross",
    "path2sda": "Path to Wesrin Cross",
    "sd_r1": "Wesrin Cross",
    "sd_r2": "Wesrin Cross",
    "path2dm": "Glitterdelve",
    "dm_r10": "Glitterdelve Mine",
    "dm_r11": "Glitterdelve Mine",
    "dm_r2": "Glitterdelve Mine",
    "dm_r8": "Glitterdelve Mine",
    "dm_r8a": "Glitterdelve Mine",
    "path2nt": "Frostspire Mountain",
    "fc_r1": "Furok Cave",
    "nt_r1": "Glacern",
    "nt_r1a": "Glacern",
    "path2ac": "Frostspire Mountain",
    "id_r1": "Frostspire Mountain",
    "id_r2": "Frostspire Mountain",
    "ac_r1": "Alpine Caverns",
    "ac_r1a": "Alpine Caverns",
    "ac_r2": "Alpine Caverns",
    "ac_r2a": "Alpine Caverns",
    "ac_r3": "Alpine Caverns",
    "ac_r5": "Alpine Caverns",
    "mm_r1": "Jeriah's Trading Post",
    "lc_r1a": "Lava Caves",
    "lc_r5": "Ice Caves",
    "lc_r5a": "Ice Caves",
    "sr_r1": "Subterranean River",
    "sr_r2": "Subterranean River",
    "sr_r3": "Subterranean River",
    "sr_r4": "Subterranean River",
    "sr_side": "Subterranean River",
    "df_bandits": "Dark Forest",
    "df_r0": "Traveler Camp",
    "df_r1": "Dark Forest",
    "ds_r1": "Eastern Swamp",
    "ds_r2": "Eastern Swamp",
    "ds_r2a": "Eastern Swamp",
    "gi_r1": "Goblin Lair",
    "gi_r10": "Goblin Lair",
    "gi_r10a": "Goblin Lair",
    "gi_r11": "Goblin Lair",
    "gi_r3": "Goblin Lair",
    "gi_r3b": "Goblin Lair",
    "gi_r3_b": "Goblin Lair",
    "gi_r4": "Goblin Lair",
    "gi_r5": "Goblin Lair",
    "gi_r5a": "Goblin Lair",
    "fd_r1": "Fury Den (Ehb)",
    "cf_r1": "Fortress Kroth",
    "cf_r1a": "Fortress Kroth",
    "hs_r1": "Hall of Skulls",
    "dc_r0": "Cliffs of Fire",
    "dc_r1": "Droog Village",
    "dc_r1a": "Droog Village",
    "dc_r2": "Dragon's Rathe",
    "dl_r1": "Dragon's Rathe",
    "ce_r1": "Castle Ehb",
    "ce_r1a": "Castle Ehb",
    "ce_r2": "Castle Ehb",
    "ce_r2a": "Castle Ehb",
    "cd_r1": "Castle Dungeon",
    "gd_a_r1": "Chamber of Stars",
    "gl_r1": "Gom's Lair",
    "gom2": "Vault of Eternity",
    "tr_r1": "Temple Ruins",
    "tr_r2": "Bonepickers' Homes",
    "tr_r3": "Fury Cave Entrance",
    "tr_r3a": "Mushroom Cave",
    "wd_r1": "Bonepicker's Dungeon",
    "wd_r1a": "Goblin Base Secret Dungeon",
}


def resolve_region_name(region_id: str) -> str:
    return REGION_NAMES.get(region_id, f"Unknown ({region_id})")
